Ingredient.create(name: "Lemon")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Coca")
Ingredient.create(name: "Light rum")
Ingredient.create(name: "Applejack")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Dark rum")
Ingredient.create(name: "Scotch")
Ingredient.create(name: "Triple sec")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Black vodka")
Ingredient.create(name: "Champagne")
Ingredient.create(name: "Coffee liqueur")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Sugar")
Ingredient.create(name: "Khashasha")
Ingredient.create(name: "Mint")
Ingredient.create(name: "Sugar Canne")
Ingredient.create(name: "Rhum")
Ingredient.create(name: "Grapefruit juice")
Ingredient.create(name: "Milk")
Ingredient.create(name: "Strawberries")
Ingredient.create(name: "Grapes")
Ingredient.create(name: "Kiwi")
Ingredient.create(name: "Spiced rum")
Ingredient.create(name: "Water")
