Cocktail.create(name: "Mojito", remote_photo_url: "https://res.cloudinary.com/dxgynqjm3/image/upload/v1561387380/iy4vzndooez4xezxtecr.jpg")
Cocktail.create(name: "Pina Colada", remote_photo_url: "https://res.cloudinary.com/dxgynqjm3/image/upload/v1561389304/Pina_Colada_ijotlu.jpg" )
Cocktail.create(name: "Cosmopolitan", remote_photo_url: "https://res.cloudinary.com/dxgynqjm3/image/upload/v1561389304/Cosmopolitain_qhivs3.jpg" )
Cocktail.create(name: "Gin Fizz", remote_photo_url: "https://res.cloudinary.com/dxgynqjm3/image/upload/v1561472309/Bailey_s_coffee_xzuojy.jpg" )
Cocktail.create(name: "Bailey's coffee", remote_photo_url: "https://res.cloudinary.com/dxgynqjm3/image/upload/v1561389303/GIN_Fizz_hoq0qn.jpg" )
Cocktail.create(name: "Balalaïka", remote_photo_url: "https://res.cloudinary.com/dxgynqjm3/image/upload/v1561472309/63932_w420h344c1cx500cy334_oxsuou.jpg" )
Cocktail.create(name: "Bloody Mary", remote_photo_url: "https://res.cloudinary.com/dxgynqjm3/image/upload/v1561472408/15326_w800h600c1cx1540cy1918_mdky3v.jpg" )

Ingredient.create(name: "Lemon")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Mint Leaves")
Ingredient.create(name: "Gin")
Ingredient.create(name: "White rum")
Ingredient.create(name: "Dark rum")
Ingredient.create(name: "Scotch")
Ingredient.create(name: "Apple Cider")
Ingredient.create(name: "Apple Juice")
Ingredient.create(name: "Orange")
Ingredient.create(name: "Brown Sugar")
Ingredient.create(name: "Soda Water")
